config/routes.rb
Rails.application.routes.draw do
  root to: 'brands#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :brands, only: [ :index, :show, :new, :create ] do
    resources :sponsorships, only: [ :new, :create ]
  end

  resources :sponsorships, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :sponsorships, dependent: :destroy
  has_many :players, through: :sponsorships
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/player.rb
class Player < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :sponsorships
  has_many :brands, through: :sponsorships
end

app/models/sponsorship.rb
class Sponsorship < ApplicationRecord
  belongs_to :player
  belongs_to :brand

  validates :player, uniqueness: { scope: :brand }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to brands_path
    else
      render :new
    end
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :image_url, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sponsorships_controller.rb
class SponsorshipsController < ApplicationController
  def new
    @brand = Brand.find(params[:brand_id])
    @sponsorship = Sponsorship.new
  end

  def create
    @brand = Brand.find(params[:brand_id])
    @sponsorship = Sponsorship.new(sponsorship_params)
    @sponsorship.brand = @brand
    if @sponsorship.save
      redirect_to brand_path(@sponsorship.brand)
    else
      render :new
    end
  end

  def destroy
    @sponsorship = Sponsorship.find(params[:id])
    @sponsorship.destroy
    redirect_to brand_path(@sponsorship.brand)
  end

  private

  def sponsorship_params
    params.require(:sponsorship).permit(:player_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brands/create.html.erb
<>

app/views/brands/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://indianwellstennisgarden.com/wp-content/uploads/2019/09/20190309_JS_BNPPO_DJI_0027.jpg);">
  <div class="container">
    <h1>Tennis Pro Kit</h1>
    <p>Everything the pros are using.</p>
      <%= link_to "Add Brand", new_brand_path, class:"btn btn-primary" %>
  </div>
</div>

<div class="container mb-5">
  <div class="cards mt-3 pt-2">
      <% @brands.each do |brand| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= brand.photo.attached? ? cl_image_path(brand.photo.key) : 'https://cdn.shopify.com/s/files/1/1749/5899/articles/tennis-string-101-resized_1000x.jpg?v=1541364562'%>)">
          <%= link_to brand.name, brand_path(brand) %>
        </div>
      <% end %>
  </div>
</div>

app/views/brands/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://s3.eu-west-2.amazonaws.com/luxurylondon.co.uk-storage-bucket-001/images/060319122708/card/wimbledon-london-2019-xl-hd.jpg);">
  <div class="container">
    <h1>Add a Brand</h1>
      <%= link_to "Home", brands_path, class:"btn btn-primary" %>
  </div>
</div>
<div class="container mt-3">
  <h2>What brand is going in the kitbag?</h2>
  <%= simple_form_for @brand do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "In the bag", class: "btn btn-success" %>
  <% end %>
</div>

app/views/brands/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.atptour.com/en/tournaments/roland-garros/520/-/media/images/news/2016-photo-upload/roland-garros-2015-final-stadium.jpg);">
  <div class="container">
    <h1><%= @brand.name %></h1>
      <%= link_to "Home", brands_path, class:"btn btn-primary" %>
  </div>
</div>
<div class="container p-3">
  <%= link_to "Sponsorships", new_brand_sponsorship_path(@brand), class:"btn btn-success" %>
</div>

<div class="container">
  <div class="row">
    <% @brand.sponsorships.each do |sponsorship| %>
      <div class="col-sm-4 mb-4">
        <div class="card-product">
          <%= image_tag sponsorship.player.image_url %>
        <div class="card-product-infos">
          <h2><%= sponsorship.player.name %></h2>
          <p><strong>Ranking: <%= sponsorship.player.ranking %></strong></p>
          <p>Nationality: <%= sponsorship.player.country %></p>
          <%= link_to sponsorship_path(sponsorship), method: :delete, class:'card-remove-link', data: { confirm: "Delete #{sponsorship.player.name} sponsorship?"} do %>
            <i class="fas fa-times-circle"></i>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tennis Pro Kit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/sponsorships/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://s3.eu-west-2.amazonaws.com/luxurylondon.co.uk-storage-bucket-001/images/060319122708/card/wimbledon-london-2019-xl-hd.jpg);">
  <div class="container">
    <h1>Add a Sponsorship</h1>
      <%= link_to "Home", brands_path, class:"btn btn-primary" %>
  </div>
</div>
<div class="container mt-3">
  <h2>Who is being sponsored?</h2>
  <%= simple_form_for [@brand, @sponsorship] do |f| %>
    <%= f.association :player %>
    <%= f.submit "Establish", class: "btn btn-success" %>
  <% end %>
</div>